import 'package:flutter/material.dart';

const automaticallyImplySkipNextButton = true;
const automaticallyImplySkipPreviousButton = true;
const toggleFullscreenOnDoublePress = true;
const modifyVolumeOnScroll = true;

const visibleOnMount = false;
const controlsHoverDuration = Duration(seconds: 3);
const controlsTransitionDuration = Duration(milliseconds: 150);
const topButtonBarMargin = EdgeInsets.symmetric(horizontal: 16.0);
const bottomButtonBarMargin = EdgeInsets.symmetric(horizontal: 16.0);
const buttonBarHeight = 56.0;
const buttonBarButtonSize = 28.0;
const buttonBarButtonColor = Color(0xFFFFFFFF);
const seekBarTransitionDuration = Duration(milliseconds: 300);
const seekBarThumbTransitionDuration = Duration(milliseconds: 150);
const seekBarMargin = EdgeInsets.symmetric(horizontal: 16.0);
const seekBarHeight = 3.2;
const seekBarHoverHeight = 5.6;
const seekBarContainerHeight = 36.0;
const seekBarColor = Color(0x3DFFFFFF);
const seekBarHoverColor = Color(0x3DFFFFFF);
const seekBarPositionColor = Color(0xFFFF0000);
const seekBarBufferColor = Color(0x3DFFFFFF);
const seekBarThumbSize = 12.0;
const seekBarThumbColor = Color(0xFFFF0000);
const volumeBarColor = Color(0x3DFFFFFF);
const volumeBarActiveColor = Color(0xFFFFFFFF);
const volumeBarThumbSize = 12.0;
const volumeBarThumbColor = Color(0xFFFFFFFF);
const volumeBarTransitionDuration = Duration(milliseconds: 150);
const shiftSubtitlesOnControlsVisibilityChange = true;
