import 'package:flutter/material.dart';

class MeiyouButtonStyle extends ButtonStyle {
  MeiyouButtonStyle(
      {TextStyle? textStyle,
      Color? backgroundColor,
      Color? foregroundColor,
      Color? overlayColor,
      Color? shadowColor,
      Color? surfaceTintColor,
      double? elevation,
      EdgeInsetsGeometry? padding,
      Size? minimumSize,
      Size? fixedSize,
      Size? maximumSize,
      Color? iconColor,
      double? iconSize,
      BorderSide? side,
      OutlinedBorder? shape,
      MouseCursor? mouseCursor,
      super.visualDensity,
      super.tapTargetSize,
      super.animationDuration,
      super.enableFeedback,
      super.alignment,
      super.splashFactory,
      s
      // /  super.splashFactory,
      })
      : super(
          textStyle: MaterialStatePropertyAll(textStyle),
          backgroundColor: MaterialStatePropertyAll(backgroundColor),
          foregroundColor: MaterialStatePropertyAll(foregroundColor),
          overlayColor: MaterialStatePropertyAll(overlayColor),
          shadowColor: MaterialStatePropertyAll(shadowColor),
          surfaceTintColor: MaterialStatePropertyAll(surfaceTintColor),
          elevation: MaterialStatePropertyAll(elevation),
          padding: MaterialStatePropertyAll(padding),
          minimumSize: MaterialStatePropertyAll(minimumSize),
          fixedSize: MaterialStatePropertyAll(fixedSize),
          maximumSize: MaterialStatePropertyAll(maximumSize),
          iconColor: MaterialStatePropertyAll(iconColor),
          iconSize: MaterialStatePropertyAll(iconSize),
          side: MaterialStatePropertyAll(side),
          shape: MaterialStatePropertyAll(shape),
          mouseCursor: MaterialStatePropertyAll(mouseCursor),
        );

  // factory MeiyouButtonStyle.overWriteAllPropertyAsMaterialState({
  //   TextStyle? textStyle,
  //   Color? backgroundColor,
  //   Color? foregroundColor,
  //   Color? overlayColor,
  //   Color? shadowColor,
  //   Color? surfaceTintColor,
  //   double? elevation,
  //   EdgeInsetsGeometry? padding,
  //   Size? minimumSize,
  //   Size? fixedSize,
  //   Size? maximumSize,
  //   Color? iconColor,
  //   double? iconSize,
  //   BorderSide? side,
  //   OutlinedBorder? shape,
  //   MouseCursor? mouseCursor,
  //   VisualDensity? visualDensity,
  //   MaterialTapTargetSize? tapTargetSize,
  //   Duration? animationDuration,
  //   bool? enableFeedback,
  //   AlignmentGeometry? alignment,
  //   InteractiveInkFeatureFactory? splashFactory,
  // }) {
  //   return MeiyouButtonStyle();
  // }
}
